steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - '-c'
      - |
        gcloud --project=sponge-recruit-gavin container clusters get-credentials cluster-1 --zone europe-west2-a
        kubectl get pods -A
        kubectl create namespace testcw
        kubectl get ns
        kubectl delete namespace testcw
        kubectl get ns
